"""baseline schema

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-02 23:15:22.030663

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS bot"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_client",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "disabled", name="application_client_status"),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id"),
        schema="auth",
    )
    op.create_table(
        "auth_audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("principal_type", sa.String(), nullable=True),
        sa.Column("principal_id", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_index("ix_auth_audit_log_created_at", "auth_audit_log", ["created_at"], unique=False, schema="auth")
    op.create_index(
        "ix_auth_audit_log_principal_type_id_created_at",
        "auth_audit_log",
        ["principal_type", "principal_id", "created_at"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "permission_scope",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
        schema="auth",
    )
    op.create_table(
        "app_command_audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=True),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column("discord_id", sa.BigInteger(), nullable=True),
        sa.Column("command_name", sa.Text(), nullable=False),
        sa.Column("permission_action", sa.Text(), nullable=True),
        sa.Column("permission_allowed", sa.Boolean(), nullable=True),
        sa.Column("permission_source", sa.Text(), nullable=True),
        sa.Column("permission_reason", sa.Text(), nullable=True),
        sa.Column("error_type", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="bot",
    )
    op.create_index(
        "ix_app_command_audit_log_created_at", "app_command_audit_log", ["created_at"], unique=False, schema="bot"
    )
    op.create_index(
        "ix_app_command_audit_log_discord_id_created_at",
        "app_command_audit_log",
        ["discord_id", "created_at"],
        unique=False,
        schema="bot",
    )
    op.create_index(
        "ix_app_command_audit_log_guild_id_command_name_created_at",
        "app_command_audit_log",
        ["guild_id", "command_name", "created_at"],
        unique=False,
        schema="bot",
    )
    op.create_table(
        "discord_guild",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("guild_id"),
        schema="bot",
    )
    op.create_index(
        "uq_discord_guild_primary_active",
        "discord_guild",
        ["is_primary"],
        unique=True,
        schema="bot",
        postgresql_where=sa.text("is_primary IS true AND active IS true"),
    )
    op.create_table(
        "discord_user",
        sa.Column("discord_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("role", sa.Enum("admin", "tutor", "student", name="member_role", schema="bot"), nullable=False),
        sa.Column("nick_name", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("nick_name <> ''", name="ck_discord_user_nick_name_not_empty"),
        sa.PrimaryKeyConstraint("discord_id"),
        schema="bot",
    )
    op.create_index("ix_discord_user_role_active", "discord_user", ["role", "active"], unique=False, schema="bot")
    op.create_table(
        "permission_grant",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "subject_type",
            sa.Enum("role", "group", "user", name="permission_subject_type", schema="bot"),
            nullable=False,
        ),
        sa.Column("subject_key", sa.Text(), nullable=False),
        sa.Column("action_key", sa.Text(), nullable=False),
        sa.Column("effect", sa.Enum("allow", "deny", name="permission_grant_effect", schema="bot"), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_type", "subject_key", "action_key", name="uq_permission_grant_subject_action"),
        schema="bot",
    )
    op.create_index("ix_permission_grant_action_key", "permission_grant", ["action_key"], unique=False, schema="bot")
    op.create_index(
        "ix_permission_grant_subject_type_subject_key_active",
        "permission_grant",
        ["subject_type", "subject_key", "active"],
        unique=False,
        schema="bot",
    )
    op.create_table(
        "permission_group",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
        schema="bot",
    )
    op.create_table(
        "party",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("PERSON", "COMPANY", name="party_type"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="core",
    )
    op.create_table(
        "subject",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="core",
    )
    op.create_table(
        "plz_ort",
        sa.Column("plz", sa.String(length=5), nullable=False),
        sa.Column("ort", sa.String(), nullable=False),
        sa.Column("landkreis", sa.String(), nullable=False),
        sa.Column("bundesland", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("plz", "ort"),
        schema="geo",
    )
    op.create_table(
        "application_client_scope_grant",
        sa.Column("application_client_id", sa.UUID(), nullable=False),
        sa.Column("scope_key", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["application_client_id"], ["auth.application_client.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scope_key"], ["auth.permission_scope.key"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("application_client_id", "scope_key"),
        schema="auth",
    )
    op.create_table(
        "application_client_secret",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_client_id", sa.UUID(), nullable=False),
        sa.Column("secret_hash", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["application_client_id"], ["auth.application_client.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_index(
        "ix_application_client_secret_application_client_id",
        "application_client_secret",
        ["application_client_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "discord_channel",
        sa.Column("channel_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("parent_channel_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("category", "text", "voice", "thread", "forum", name="discord_channel_type", schema="bot"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("managed_by_bot", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id", "parent_channel_id"],
            ["bot.discord_channel.guild_id", "bot.discord_channel.channel_id"],
            name="fk_discord_channel_parent",
            ondelete="SET NULL (parent_channel_id)",
        ),
        sa.ForeignKeyConstraint(["guild_id"], ["bot.discord_guild.guild_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("channel_id"),
        sa.UniqueConstraint("guild_id", "channel_id", name="uq_discord_channel_guild_id_channel_id"),
        schema="bot",
    )
    op.create_index(
        "ix_discord_channel_guild_id_deleted_at",
        "discord_channel",
        ["guild_id", "deleted_at"],
        unique=False,
        schema="bot",
    )
    op.create_index(
        "ix_discord_channel_parent_channel_id", "discord_channel", ["parent_channel_id"], unique=False, schema="bot"
    )
    op.create_table(
        "discord_role_binding",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        # member_role enum is created above by the discord_user table; do not re-create it here.
        sa.Column(
            "member_role",
            postgresql.ENUM("admin", "tutor", "student", name="member_role", schema="bot", create_type=False),
            nullable=False,
        ),
        sa.Column("role_id", sa.BigInteger(), nullable=True),
        sa.Column("role_name", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["guild_id"], ["bot.discord_guild.guild_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("guild_id", "member_role"),
        schema="bot",
    )
    op.create_table(
        "discord_user_permission_group",
        sa.Column("discord_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("group_key", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["discord_id"], ["bot.discord_user.discord_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_key"], ["bot.permission_group.key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("discord_id", "group_key"),
        schema="bot",
    )
    op.create_table(
        "company",
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["party_id"], ["core.party.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("party_id"),
        schema="core",
    )
    op.create_table(
        "contact_info",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("EMAIL", "PHONE", name="contact_info_type"), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["party_id"], ["core.party.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("party_id", "type", "value", name="uq_contact_info"),
        schema="core",
    )
    op.create_index(op.f("ix_core_contact_info_party_id"), "contact_info", ["party_id"], unique=False, schema="core")
    op.create_table(
        "party_relation",
        sa.Column("from_party_id", sa.UUID(), nullable=False),
        sa.Column("to_party_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("PARENT_OF", "TUTOR_OF", "PAYS_FOR", name="party_relation_type"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["from_party_id"], ["core.party.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_party_id"], ["core.party.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("from_party_id", "to_party_id", "type"),
        schema="core",
    )
    op.create_table(
        "person",
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("lastname", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["party_id"], ["core.party.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("party_id"),
        schema="core",
    )
    op.create_table(
        "clockodo_customer",
        sa.Column("clockodo_customer_id", sa.String(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["party_id"], ["core.party.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("clockodo_customer_id"),
        sa.UniqueConstraint("party_id"),
        schema="ext",
    )
    op.create_table(
        "clockodo_project",
        sa.Column("clockodo_project_id", sa.String(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["party_id"], ["core.party.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("clockodo_project_id"),
        sa.UniqueConstraint("party_id"),
        schema="ext",
    )
    op.create_table(
        "discord_account",
        # discord_id starts as String to match the pre-Alembic production schema; it is
        # converted to BigInteger by revision 0002_discord_id_bigint.
        # is_primary and active did not exist in the pre-Alembic schema; they are added
        # by revision 0004_discord_account_flags.
        sa.Column("discord_id", sa.String(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["party_id"], ["core.party.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("discord_id"),
        sa.UniqueConstraint("party_id", name="discord_account_party_id_key"),
        schema="ext",
    )
    op.create_table(
        "microsoft_account",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["party_id"], ["core.party.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("party_id"),
        schema="ext",
    )
    op.create_table(
        "microsoft_contact",
        sa.Column("contact_id", sa.String(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["party_id"], ["core.party.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("contact_id"),
        sa.UniqueConstraint("party_id"),
        schema="ext",
    )
    op.create_table(
        "sevdesk_contact",
        sa.Column("sevdesk_id", sa.String(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["party_id"], ["core.party.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sevdesk_id"),
        sa.UniqueConstraint("party_id"),
        schema="ext",
    )
    op.create_table(
        "archive_category",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("archive_no", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("category_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("capacity", sa.SmallInteger(), server_default=sa.text("50"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("archive_no > 0", name="ck_archive_category_archive_no_positive"),
        sa.CheckConstraint("capacity BETWEEN 1 AND 50", name="ck_archive_category_capacity"),
        sa.ForeignKeyConstraint(
            ["guild_id", "category_channel_id"],
            ["bot.discord_channel.guild_id", "bot.discord_channel.channel_id"],
            name="fk_archive_category_channel",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["guild_id"], ["bot.discord_guild.guild_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("guild_id", "archive_no"),
        sa.UniqueConstraint("category_channel_id", name="uq_archive_category_category_channel_id"),
        sa.UniqueConstraint("guild_id", "category_channel_id", name="uq_archive_category_guild_id_category_channel_id"),
        schema="bot",
    )
    op.create_index("ix_archive_category_guild_id", "archive_category", ["guild_id"], unique=False, schema="bot")
    op.create_table(
        "command_env_channel",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("channel_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("kind", sa.Enum("admin_cmd", "tutor_cmd", name="command_env_kind", schema="bot"), nullable=False),
        sa.Column("owner_discord_id", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id", "channel_id"],
            ["bot.discord_channel.guild_id", "bot.discord_channel.channel_id"],
            name="fk_command_env_channel_channel",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["guild_id"], ["bot.discord_guild.guild_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_discord_id"], ["bot.discord_user.discord_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("guild_id", "channel_id", "kind"),
        schema="bot",
    )
    op.create_index(
        "ix_command_env_channel_guild_id_kind", "command_env_channel", ["guild_id", "kind"], unique=False, schema="bot"
    )
    op.create_index(
        "ix_command_env_channel_guild_id_owner_discord_id_kind",
        "command_env_channel",
        ["guild_id", "owner_discord_id", "kind"],
        unique=False,
        schema="bot",
    )
    op.create_index(
        "uq_command_env_channel_guild_id_owner_discord_id_kind",
        "command_env_channel",
        ["guild_id", "owner_discord_id", "kind"],
        unique=True,
        schema="bot",
        postgresql_where=sa.text("owner_discord_id IS NOT NULL"),
    )
    op.create_table(
        "tutor_workspace",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("tutor_discord_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("category_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("command_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("student_channel_capacity", sa.SmallInteger(), server_default=sa.text("49"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "student_channel_capacity BETWEEN 0 AND 49", name="ck_tutor_workspace_student_channel_capacity"
        ),
        sa.ForeignKeyConstraint(
            ["guild_id", "category_channel_id"],
            ["bot.discord_channel.guild_id", "bot.discord_channel.channel_id"],
            name="fk_tutor_workspace_category_channel",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["guild_id", "command_channel_id"],
            ["bot.discord_channel.guild_id", "bot.discord_channel.channel_id"],
            name="fk_tutor_workspace_command_channel",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["guild_id"], ["bot.discord_guild.guild_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tutor_discord_id"], ["bot.discord_user.discord_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("guild_id", "tutor_discord_id"),
        sa.UniqueConstraint("category_channel_id", name="uq_tutor_workspace_category_channel_id"),
        sa.UniqueConstraint("command_channel_id", name="uq_tutor_workspace_command_channel_id"),
        schema="bot",
    )
    op.create_table(
        "student",
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column(
            "preferred_meeting_tool",
            sa.Enum("DISCORD", "IN_PERSON", "MICROSOFT_TEAMS", "PHONE", name="preferred_meeting_tool"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["core.person.party_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("person_id"),
        schema="core",
    )
    op.create_table(
        "tutor",
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["core.person.party_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("person_id"),
        schema="core",
    )
    op.create_table(
        "student_workspace",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("student_discord_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("tutor_discord_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "channel_state",
            sa.Enum("tutor_category", "archive_category", name="student_channel_state", schema="bot"),
            server_default=sa.text("'tutor_category'"),
            nullable=False,
        ),
        sa.Column("current_parent_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("archive_category_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("stashed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("popped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(channel_state = 'tutor_category' AND archive_category_channel_id IS NULL) OR (channel_state = 'archive_category' AND archive_category_channel_id IS NOT NULL)",
            name="ck_student_workspace_archive_category_matches_state",
        ),
        sa.CheckConstraint(
            "channel_state <> 'archive_category' OR channel_id IS NOT NULL",
            name="ck_student_workspace_archive_requires_channel",
        ),
        sa.CheckConstraint(
            "channel_state <> 'archive_category' OR current_parent_channel_id = archive_category_channel_id",
            name="ck_student_workspace_archive_parent",
        ),
        sa.CheckConstraint(
            "channel_state <> 'tutor_category' OR channel_id IS NULL OR current_parent_channel_id IS NOT NULL",
            name="ck_student_workspace_tutor_category_parent",
        ),
        sa.ForeignKeyConstraint(
            ["guild_id", "archive_category_channel_id"],
            ["bot.archive_category.guild_id", "bot.archive_category.category_channel_id"],
            name="fk_student_workspace_archive_category",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["guild_id", "channel_id"],
            ["bot.discord_channel.guild_id", "bot.discord_channel.channel_id"],
            name="fk_student_workspace_channel",
            ondelete="SET NULL (channel_id)",
        ),
        sa.ForeignKeyConstraint(
            ["guild_id", "current_parent_channel_id"],
            ["bot.discord_channel.guild_id", "bot.discord_channel.channel_id"],
            name="fk_student_workspace_current_parent_channel",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["guild_id"], ["bot.discord_guild.guild_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_discord_id"], ["bot.discord_user.discord_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tutor_discord_id"], ["bot.discord_user.discord_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("guild_id", "student_discord_id"),
        sa.UniqueConstraint("channel_id", name="uq_student_workspace_channel_id"),
        schema="bot",
    )
    op.create_index(
        "ix_student_workspace_archive_category_channel_id_channel_state",
        "student_workspace",
        ["archive_category_channel_id", "channel_state"],
        unique=False,
        schema="bot",
    )
    op.create_index(
        "ix_student_workspace_guild_id_channel_state",
        "student_workspace",
        ["guild_id", "channel_state"],
        unique=False,
        schema="bot",
    )
    op.create_index(
        "ix_student_workspace_guild_id_tutor_discord_id",
        "student_workspace",
        ["guild_id", "tutor_discord_id"],
        unique=False,
        schema="bot",
    )
    op.create_index(
        "ix_student_workspace_guild_id_tutor_discord_id_channel_state",
        "student_workspace",
        ["guild_id", "tutor_discord_id", "channel_state"],
        unique=False,
        schema="bot",
    )
    op.create_table(
        "student_subject",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["core.student.person_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subject_id"], ["core.subject.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("student_id", "subject_id"),
        schema="core",
    )
    op.create_table(
        "tutor_subject",
        sa.Column("tutor_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["subject_id"], ["core.subject.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tutor_id"], ["core.tutor.person_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tutor_id", "subject_id"),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tutor_subject", schema="core")
    op.drop_table("student_subject", schema="core")
    op.drop_index(
        "ix_student_workspace_guild_id_tutor_discord_id_channel_state", table_name="student_workspace", schema="bot"
    )
    op.drop_index("ix_student_workspace_guild_id_tutor_discord_id", table_name="student_workspace", schema="bot")
    op.drop_index("ix_student_workspace_guild_id_channel_state", table_name="student_workspace", schema="bot")
    op.drop_index(
        "ix_student_workspace_archive_category_channel_id_channel_state", table_name="student_workspace", schema="bot"
    )
    op.drop_table("student_workspace", schema="bot")
    op.drop_table("tutor", schema="core")
    op.drop_table("student", schema="core")
    op.drop_table("tutor_workspace", schema="bot")
    op.drop_index(
        "uq_command_env_channel_guild_id_owner_discord_id_kind",
        table_name="command_env_channel",
        schema="bot",
        postgresql_where=sa.text("owner_discord_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_command_env_channel_guild_id_owner_discord_id_kind", table_name="command_env_channel", schema="bot"
    )
    op.drop_index("ix_command_env_channel_guild_id_kind", table_name="command_env_channel", schema="bot")
    op.drop_table("command_env_channel", schema="bot")
    op.drop_index("ix_archive_category_guild_id", table_name="archive_category", schema="bot")
    op.drop_table("archive_category", schema="bot")
    op.drop_table("sevdesk_contact", schema="ext")
    op.drop_table("microsoft_contact", schema="ext")
    op.drop_table("microsoft_account", schema="ext")
    op.drop_table("discord_account", schema="ext")
    op.drop_table("clockodo_project", schema="ext")
    op.drop_table("clockodo_customer", schema="ext")
    op.drop_table("person", schema="core")
    op.drop_table("party_relation", schema="core")
    op.drop_index(op.f("ix_core_contact_info_party_id"), table_name="contact_info", schema="core")
    op.drop_table("contact_info", schema="core")
    op.drop_table("company", schema="core")
    op.drop_table("discord_user_permission_group", schema="bot")
    op.drop_table("discord_role_binding", schema="bot")
    op.drop_index("ix_discord_channel_parent_channel_id", table_name="discord_channel", schema="bot")
    op.drop_index("ix_discord_channel_guild_id_deleted_at", table_name="discord_channel", schema="bot")
    op.drop_table("discord_channel", schema="bot")
    op.drop_index(
        "ix_application_client_secret_application_client_id", table_name="application_client_secret", schema="auth"
    )
    op.drop_table("application_client_secret", schema="auth")
    op.drop_table("application_client_scope_grant", schema="auth")
    op.drop_table("plz_ort", schema="geo")
    op.drop_table("subject", schema="core")
    op.drop_table("party", schema="core")
    op.drop_table("permission_group", schema="bot")
    op.drop_index("ix_permission_grant_subject_type_subject_key_active", table_name="permission_grant", schema="bot")
    op.drop_index("ix_permission_grant_action_key", table_name="permission_grant", schema="bot")
    op.drop_table("permission_grant", schema="bot")
    op.drop_index("ix_discord_user_role_active", table_name="discord_user", schema="bot")
    op.drop_table("discord_user", schema="bot")
    op.drop_index(
        "uq_discord_guild_primary_active",
        table_name="discord_guild",
        schema="bot",
        postgresql_where=sa.text("is_primary IS true AND active IS true"),
    )
    op.drop_table("discord_guild", schema="bot")
    op.drop_index(
        "ix_app_command_audit_log_guild_id_command_name_created_at", table_name="app_command_audit_log", schema="bot"
    )
    op.drop_index("ix_app_command_audit_log_discord_id_created_at", table_name="app_command_audit_log", schema="bot")
    op.drop_index("ix_app_command_audit_log_created_at", table_name="app_command_audit_log", schema="bot")
    op.drop_table("app_command_audit_log", schema="bot")
    op.drop_table("permission_scope", schema="auth")
    op.drop_index("ix_auth_audit_log_principal_type_id_created_at", table_name="auth_audit_log", schema="auth")
    op.drop_index("ix_auth_audit_log_created_at", table_name="auth_audit_log", schema="auth")
    op.drop_table("auth_audit_log", schema="auth")
    op.drop_table("application_client", schema="auth")

    op.execute(sa.text("DROP TYPE IF EXISTS bot.command_env_kind"))
    op.execute(sa.text("DROP TYPE IF EXISTS bot.discord_channel_type"))
    op.execute(sa.text("DROP TYPE IF EXISTS bot.member_role"))
    op.execute(sa.text("DROP TYPE IF EXISTS bot.permission_grant_effect"))
    op.execute(sa.text("DROP TYPE IF EXISTS bot.permission_subject_type"))
    op.execute(sa.text("DROP TYPE IF EXISTS bot.student_channel_state"))
    op.execute(sa.text("DROP TYPE IF EXISTS public.application_client_status"))
    op.execute(sa.text("DROP TYPE IF EXISTS public.contact_info_type"))
    op.execute(sa.text("DROP TYPE IF EXISTS public.party_relation_type"))
    op.execute(sa.text("DROP TYPE IF EXISTS public.party_type"))
    op.execute(sa.text("DROP TYPE IF EXISTS public.preferred_meeting_tool"))
    # ### end Alembic commands ###
    op.execute(sa.text("DROP SCHEMA IF EXISTS bot"))
