"""add bot.job

Revision ID: 0003_job
Revises: 0002_discord_id_bigint
Create Date: 2026-06-02 23:20:04.349000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003_job"
down_revision: str | None = "0002_discord_id_bigint"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "claimed", "completed", "failed", name="job_status", schema="bot"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("attempt", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), server_default=sa.text("5"), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("attempt >= 0", name="ck_job_attempt_non_negative"),
        sa.CheckConstraint("max_attempts >= 1", name="ck_job_max_attempts_positive"),
        sa.PrimaryKeyConstraint("job_id"),
        schema="bot",
    )
    op.create_index(
        "ix_job_claimable",
        "job",
        ["available_at"],
        unique=False,
        schema="bot",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index("ix_job_kind_status", "job", ["kind", "status"], unique=False, schema="bot")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_kind_status", table_name="job", schema="bot")
    op.drop_index("ix_job_claimable", table_name="job", schema="bot", postgresql_where=sa.text("status = 'pending'"))
    op.drop_table("job", schema="bot")
    # Drop the enum type too so the migration can be re-applied after a downgrade.
    op.execute(sa.text("DROP TYPE IF EXISTS bot.job_status"))
    # ### end Alembic commands ###
