"""add bot.operation

Revision ID: 0005_operation
Revises: 0004_discord_account_flags
Create Date: 2026-06-03 13:56:47.510189

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0005_operation"
down_revision: str | None = "0004_discord_account_flags"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operation",
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "tutor_activate",
                "student_activate",
                "student_stash",
                "student_pop",
                name="operation_kind",
                schema="bot",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("prepared", "committed", "expired", "failed", name="operation_status", schema="bot"),
            server_default=sa.text("'prepared'"),
            nullable=False,
        ),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("subject_discord_id", sa.BigInteger(), nullable=False),
        sa.Column("tutor_discord_id", sa.BigInteger(), nullable=True),
        sa.Column("reserved_archive_category_channel_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "plan", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("operation_id"),
        schema="bot",
    )
    op.create_index(
        "ix_operation_reservation",
        "operation",
        ["guild_id", "reserved_archive_category_channel_id"],
        unique=False,
        schema="bot",
        postgresql_where=sa.text("status = 'prepared' AND reserved_archive_category_channel_id IS NOT NULL"),
    )
    op.create_index("ix_operation_status_expires_at", "operation", ["status", "expires_at"], unique=False, schema="bot")
    op.create_index(
        "ix_operation_subject", "operation", ["guild_id", "subject_discord_id", "status"], unique=False, schema="bot"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_operation_subject", table_name="operation", schema="bot")
    op.drop_index("ix_operation_status_expires_at", table_name="operation", schema="bot")
    op.drop_index(
        "ix_operation_reservation",
        table_name="operation",
        schema="bot",
        postgresql_where=sa.text("status = 'prepared' AND reserved_archive_category_channel_id IS NOT NULL"),
    )
    op.drop_table("operation", schema="bot")
    # Drop the enum types too so the migration can be re-applied after a downgrade.
    op.execute(sa.text("DROP TYPE IF EXISTS bot.operation_status"))
    op.execute(sa.text("DROP TYPE IF EXISTS bot.operation_kind"))
    # ### end Alembic commands ###
