"""add system.worker_heartbeat

Revision ID: 0006_worker_heartbeat
Revises: 0005_operation
Create Date: 2026-06-07 22:05:36.190909

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0006_worker_heartbeat"
down_revision: str | None = "0005_operation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_heartbeat",
        sa.Column("worker_name", sa.Text(), nullable=False),
        sa.Column("last_beat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_status", sa.Enum("ok", "degraded", name="worker_cycle_status", schema="system"), nullable=False
        ),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("worker_name"),
        schema="system",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("worker_heartbeat", schema="system")
    op.execute(sa.text("DROP TYPE IF EXISTS system.worker_cycle_status"))
    # ### end Alembic commands ###
