"""add the user account, session and action token tables

Revision ID: 0011_user_accounts
Revises: 0010_subject_title_unique
Create Date: 2026-09-20 22:43:39.064235

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011_user_accounts"
down_revision: str | None = "0010_subject_title_unique"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_account",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("invited", "active", "disabled", name="user_account_status"),
            server_default=sa.text("'invited'"),
            nullable=False,
        ),
        sa.Column("failed_login_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("email = lower(email)", name="ck_user_account_email_lowercase"),
        sa.ForeignKeyConstraint(["party_id"], ["core.party.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("party_id"),
        schema="auth",
    )
    op.create_table(
        "user_account_role",
        sa.Column("user_account_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Enum("admin", name="user_account_role_name"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_account_id"], ["auth.user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_account_id", "role"),
        schema="auth",
    )
    op.create_table(
        "user_action_token",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_account_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.Enum("invitation", "password_reset", name="user_action_token_purpose"), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_by", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_account_id"], ["auth.user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
        schema="auth",
    )
    op.create_index(
        "ix_user_action_token_user_account_id", "user_action_token", ["user_account_id"], unique=False, schema="auth"
    )
    op.create_table(
        "user_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_account_id", sa.UUID(), nullable=False),
        sa.Column("application_client_id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("refresh_token_hash", sa.Text(), nullable=False),
        sa.Column("previous_refresh_token_hash", sa.Text(), nullable=True),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["application_client_id"], ["auth.application_client.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_account_id"], ["auth.user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("previous_refresh_token_hash"),
        sa.UniqueConstraint("refresh_token_hash"),
        schema="auth",
    )
    op.create_index("ix_user_session_user_account_id", "user_session", ["user_account_id"], unique=False, schema="auth")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_session_user_account_id", table_name="user_session", schema="auth")
    op.drop_table("user_session", schema="auth")
    op.drop_index("ix_user_action_token_user_account_id", table_name="user_action_token", schema="auth")
    op.drop_table("user_action_token", schema="auth")
    op.drop_table("user_account_role", schema="auth")
    op.drop_table("user_account", schema="auth")
    # ### end Alembic commands ###
    # Postgres does not drop an enum type along with the table that used it - drop the three new
    # types explicitly, the way the baseline (0001) does for every enum it introduces.
    op.execute(sa.text("DROP TYPE IF EXISTS public.user_account_role_name"))
    op.execute(sa.text("DROP TYPE IF EXISTS public.user_account_status"))
    op.execute(sa.text("DROP TYPE IF EXISTS public.user_action_token_purpose"))
